[build]
  command = "bash build.sh"
  publish = "."

[[redirects]]
  from = "/submit_contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/submit_inquiry"
  to = "/.netlify/functions/inquiry"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions" 